@startuml

class Appointment{
-appointmentBeginDate:ptime
-appointmentEndDate:ptime
-appointmentId:usigned int
-appointmentCost:unsigned int
+getInfo():string
+finishAppointment(): unsigned int
}

Appointment --> Patient
Appointment --> Service
Appointment --> "0..*" Personnel : lista personelu >
Appointment --> Room

!ifndef UKRYJ_NOTATKI

note right of Appointment
Klasa reprezentująca spotkanie z personelem.
appointmentId - identyfikator spotkania.
appointmentBeginDate - data rozpoczęcia spotkania
appointmentEndDate - data zakończenia spotkania, obliczana
na podstawie czasu trwania usługi
appointmentCost - koszt spotkania wyliczony dodając koszt
prestiżu przydzielonych lekarzy i koszt usługi.
Klasa ta zawiera wskaznik do pacjenta, usługi i zawiera liste
przydzielonego personelu do danej usługi i do pokoju w którym
spotkanie się odbędzie.
Przelicza całkowity koszt wizyty dodajc koszt prestizu lekarzy i uslugi
Można tyko raz tego uzyc
Zwraca ostateczny koszt po przeliczeniu.
end note

!endif

@enduml