@startuml

abstract class Person{
-name:string
-lastName:string
-isArchive:bool
+ {abstract} getInfo(): string
}

!ifndef UKRYJ_NOTATKI

note right of Person
Abstrakcyjna klasa reprezentująca
człowieka.
isArchive - prezentuje czy dany człowiek jest archiwalny.
end note

!endif

abstract class Personnel{}

Person <|-- Personnel
Person <|-- Patient

@enduml