@startuml

abstract class Person{
-name:string
-lastName:string
+ {abstract} getInfo(): string
}

!ifndef UKRYJ_NOTATKI

note right of Person
Abstrakcyjna klasa reprezentująca
człowieka.
end note

!endif

abstract class Personnel{}

Person <|-- Personnel
Person <|-- Patient

@enduml