@startuml

class Rehabillitation{
-requiredEqupiment: vector<equpiment>
-requiredNurseSize: unsigned int
+getInfo():string
}


enum Equipment

Rehabillitation --> Equipment : lista sprzętu >


!ifndef UKRYJ_NOTATKI

note right of Rehabillitation
Klasa reprezentująca zabieg.
requiredEqupiment - lista sprzętu,
potrzebnego do przeprowadzenia zabiegu.
requiredNurseSize - liczba potrzbnych pięleniarek do przeprowadzenia
zabiegu
end note

!endif


@enduml