@startuml

abstract class Service{
-serviceCost:unsigned int
-serviceDuration:unsigned int
-serviceName:string
-serviceId:unsigned int
-requiredDoctorSize: unsigned int
-requiredDoctorSpec:specialisation
-isAvailble:bool
-isArchive:bool
+{abstract}getInfo():string
}

Service <|-- Consultation
Service <|-- Rehabillitation

!ifndef UKRYJ_NOTATKI

note right of Service
Abstrakcyjna klasa reprezentująca usługę.
serviceCost - koszt usługi, wliczającą koszt pielęgniarek i
podstawową stawkę doktora
serviceDuration - czas w minutach trwania usługi
serviceName - nazwa usługi
serviceId - unikalny numer usługi
requiredDoctorSize - wymagana liczba lekarzy
requiredDoctorSpec - wymagane specjalności lekarza
isAvailable - czy jest dostępna dana usługa -
potrzebne do przeprowadzenia usługi
isArchive - czy jest archiwalna
end note

!endif
@enduml