@startuml

enum Equipment {
    NONE,
    PHYSICAL_THERAPY_DEVICE,
    KINESITHERAPY_SPACE,
    ROBOTIC_SYSTEM
}

note right of Equipment
Typ wyliczeniowy zawierający cały sprzęt mogący
być potrzebny przez daną rehabilitacje i będący
dostępny w danym pokoju.
end note

@enduml