@startuml

enum Specialisation {
    PHYSIOTHERAPIST,
    ORTHOPEDIST,
    NEUROLOGIST,
    SPORTS_MEDICINE,
    OSTEOPATH,
    MASSAGE_THERAPIST,
    RHEUMATOLOGIST
}

!ifndef UKRYJ_NOTATKI

note right of Specialisation
Typ wyliczeniowy zawierający wszystkie
specjalności.
end note

!endif


@enduml