@startuml

class LogicManager {
+getPersonnelManager():PersonnelManager
+getPatientManager():PatientManager
+getServiceManager():ServiceManager
+getAppointmentManager():AppointmentManager

+removePersonnel(personnelId:unsigned int):void
+unregisterPatient(personalID:string):bool
+removeRoom(roomNumber:unsigned int):void
+removeService(serviceID:unsigned int):bool
}

LogicManager *--> AppointmentManager
LogicManager *--> PatientManager
LogicManager *--> PersonnelManager
LogicManager *--> ServiceManager
LogicManager *--> RoomManager


!ifndef UKRYJ_NOTATKI

note right of LogicManager
Klasa zawierającą wszystkie obiekty zarządców.
Klasa ta również obsługuje wszelkiego rodzaju archiwizacje
danych z uwagi na dostęp do zasobów
potrzebnych do zadecydowania czy dany
zasób można usunąć lub by ewentualnie
dokonać jakiś czyności przed
usunięciem.
removePersonnel - sprawia że osoba z personelu
staje się archiwalna, anuluje wszystkie spotkania tej osobxy i
staje się nieaktywna i archiwalna.
unregisterPatient - sprawia że pacjent staje się
archiwalny jeśli nie ma żadnych spotkań.
W zależności od sukcesu usunięcia jest zwracana wartość logiczna.
removeRoom - sprawia że pokój staje się nieaktywny, archiwalny i anuluje
wszystkie spotkania tego pokoju.
removeService - sprawia że dana usługa
staje się nie dostępna i archiwlna,
jeśli nie ma zaplanowynych już terminów
związanych z tą usługą. W zależności od sukcesu
usunięcia jest zwracany bool.
end note

!endif
@enduml