@startuml

class PatientManager {
  +getPatient(personalID:string):Patient
  +registerPatient(firstName:string, lastName:string, personalID:string, address:Address):Patient
  +findPatients(predicate:PatientPredicate):Patient[0..*]
  +findAllPatients():Patient[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of PatientManager
Klasa zarządzająca pacjentami.
registerPatient - dodaje pacjenta do repozytorium
co może się odbyć gdy pacjent nie ma zaplanowanego żadnego
spotkania.
findPatients - predykt zwracający konkretnych aktywnych  pacjentów
findAllPatients - zawraca wszystkich aktywnych pacjentów
end note

!endif

PatientManager *-> PatientRepository
PatientManager ..>Patient
PatientManager ..> PatientPredicate
@enduml