@startuml

class PatientManager {
  +registerPatient(firstName:string, lastName:string, personalID:string, address:Address):Patient
}

!ifndef UKRYJ_NOTATKI

note right of PatientManager
Klasa zarządzająca pacjentami.
registerPatient - dodaje pacjenta do repozytorium
Dziedziczy z klasy która jest tworzona na podstawie template i zawiera
odpowiednie klasy pacjenta.
end note

!endif

PatientManager *-> PatientRepository
PatientManager ..>Patient
PatientManager ..> PatientPredicate
@enduml