@startuml

class PersonnelManager {
+getPersonnel(personnelId:unsigned int):Personnel
+addDoctor(firstName:string, lastName:string, personnelId:unsigned int, specialisation:vector<specialisation>):Personnel
+addNurse(firstName:string, lastName:string, personnelId:unsigned int):Personnel
+findPersonnels(predicate:PersonnelPredicate):Personnel[0..*]
+findAll():Personnel[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of PersonnelManager
Klasa zarządzająca repozytorium personlu.
addDoctor - dodaje lekarza
addNurse - dodaje pielęgniarke
findPersonnels - predykt zwracający konkrenty niearchiwalny personel
findAll - zawraca cały niearchiwalny personel
end note

!endif

PersonnelManager *--> PersonnelRepository

PersonnelManager  ..>Personnel
PersonnelManager ..> PersonnelPredicate

@enduml