@startuml

class PersonnelManager {
+addDoctor(firstName:string, lastName:string, personnelId:unsigned int, specialisation:vector<specialisation>):Personnel
+addNurse(firstName:string, lastName:string, personnelId:unsigned int):Personnel
}

!ifndef UKRYJ_NOTATKI

note right of PersonnelManager
Klasa zarządzająca repozytorium personlu.
addDoctor - dodaje lekarza
addNurse - dodaje pielęgniarke
Dziedziczy z klasy która jest tworzona na podstawie template i zawiera
odpowiednie klasy personelu.
end note

!endif

PersonnelManager *--> PersonnelRepository

PersonnelManager  ..>Personnel
PersonnelManager ..> PersonnelPredicate

@enduml