@startuml

class RoomManager {
+addConsultationRoom(roomNumber:unsigned int):void
+addRehabillitationRoom(roomNumber:unsigned int, vector<equipment>, maxCapacity: int):void
}

!ifndef UKRYJ_NOTATKI

note right of RoomManager
Klasa zarządzająca pomieszczeniami.
addRehabillitationRoom - dodaje pokój zabiegowy
addConsultationRoom dodaje pokój konsultacyjny
Dziedziczy z klasy która jest tworzona na podstawie template i zawiera
odpowiednie klasy sal.
end note

!endif

RoomManager *--> RoomRepository
RoomManager  ..> Room
RoomManager ..> RoomPredicate
@enduml