@startuml

class RoomManager {
+getRoom(roomNumber:unsigned int):Room
+addSurgeryRoom(roomNumber:unsigned int):void
+addConsultingRoom(roomNumber:unsigned int,hasLaser: bool, hasXRay: bool, maxCapacity: int):void
+findRooms(predicate:RoomPredicate):Room[0..*]
+findAll():Rooml[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of RoomManager
Klasa zarządzająca pomieszczeniami.
addSurgeryRoom dodaje pokój zabiegowy
addConsultingRoom dodaje pokój konsultacyjny
end note

!endif

RoomManager *--> RoomRepository
RoomRepository --> Room
RoomRepository ..> RoomPredicate

@enduml