@startuml

class RoomManager {
+getRoom(roomNumber:unsigned int):Room
+addConsultationRoom(roomNumber:unsigned int):void
+addRehabillitationRoom(roomNumber:unsigned int, vector<equipment>, maxCapacity: int):void
+findRooms(predicate:RoomPredicate):Room[0..*]
+findAll():Rooml[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of RoomManager
Klasa zarządzająca pomieszczeniami.
addRehabillitationRoom - dodaje pokój zabiegowy
addConsultationRoom dodaje pokój konsultacyjny
findRooms - predykt zwracający konkrente niearchiwalne pokoje
findAll - zawraca wszystkie niearchiwalny pokoje
end note

!endif

RoomManager *--> RoomRepository
RoomManager  ..> Room
RoomManager ..> RoomPredicate
@enduml