@startuml

class RoomManager {
+getRoom(roomNumber:unsigned int):Room
+addConsultationRoom(roomNumber:unsigned int):void
+addRehabillitationRoom(roomNumber:unsigned int, hasPhysicalTherapyDevices: bool, hasKinesitherapySpace: bool, hasRoboticOrSuspensionSystem: bool, maxCapacity: int):void
+findRooms(predicate:RoomPredicate):Room[0..*]
+findAll():Rooml[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of RoomManager
Klasa zarządzająca pomieszczeniami.
addRehabillitationRoom dodaje pokój zabiegowy
addConsultationRoom dodaje pokój konsultacyjny
end note

!endif

RoomManager *--> RoomRepository
RoomRepository --> Room
RoomRepository ..> RoomPredicate

@enduml