@startuml

class ServiceManager {
  +addConsultation(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredSpecialisation:specialisation,topic:string):Service
  +addRehabillitation(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredEqupiment:vector<equipment>, requiredSpecialisation:specialisation):Service
}

!ifndef UKRYJ_NOTATKI

note right of ServiceManager
Klasa zarządzająca usługami.
addConsultation - dodaje kosnultacje
addRehabillitation - dodaje zabieg
Dziedziczy z klasy która jest tworzona na podstawie template i zawiera
odpowiednie klasy usługi.
end note

!endif

ServiceManager *--> ServiceRepository
ServiceManager  ..> Service
ServiceManager ..> ServicePredicate

@enduml