@startuml

class ServiceManager {
  +getService(serviceID:unsigned int):Service
  +addConsultation(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredSpecialisation:specialisation,topic:string):Service
  +addTreatment(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredSpecialisation:specialisation,isAnaesthesiaNeeded: bool):Service
  +findServices(predicate:ServicePredicate):Service[0..*]
  +findAllServices():Service[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of ServiceManager
Klasa zarządzająca usługami.
addConsultation - dodaje kosnultacje
addTreatment - dodaje zabieg
end note

!endif


ServiceManager *--> ServiceRepository
ServiceRepository --> Service
ServiceRepository ..> ServicePredicate

@enduml