@startuml

class ServiceManager {
  +getService(serviceID:unsigned int):Service
  +addConsultation(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredSpecialisation:specialisation,topic:string):Service
  +addRehabillitation(serviceCost:unsigned int, serviceDuration:unsigned int, serviceName:string,serviceId:unsigned int, requiredEqupiment:vector<equipment>):Service
  +findServices(predicate:ServicePredicate):Service[0..*]
  +findAllServices():Service[0..*]
}

!ifndef UKRYJ_NOTATKI

note right of ServiceManager
Klasa zarządzająca usługami.
addConsultation - dodaje kosnultacje
addRehabillitation - dodaje zabieg
findServices - predykt zwracający konkretne usługi
findAllServices - zawraca wszystkie niearchiwalne usługi
end note

!endif

ServiceManager *--> ServiceRepository

ServiceManager  ..> Service
ServiceManager ..> ServicePredicate

@enduml