@startuml

!include ../managers/appointmentManager.puml
!include ../managers/logicManager.puml
!include ../managers/patientManager.puml
!include ../managers/personnelManager.puml
!include ../managers/serviceManager.puml

@enduml