@startuml

class ConsultationRoom{
+getInfo():string
+canBeUsed(service:Service):bool
}

!ifndef UKRYJ_NOTATKI

note right of ConsultationRoom
Klasa reprezentująca salę przeznaczoną
do przeprowadzania konsultacji.
Klasa ta dziedziczy z klasy Room.
canBeUsed(service:Service) - zwraca true tylko
dla gdy usługa nie wymaga żadnego sprzętu.
end note

!endif

@enduml