@startuml

class ConsultationRoom{
+getInfo():string
+canBeUsed(equipment:Equipment):bool
}

!ifndef UKRYJ_NOTATKI

note right of ConsultationRoom
Klasa reprezentująca salę przeznaczoną
do przeprowadzania konsultacji.
Klasa ta dziedziczy z klasy Room.
canBeUsed(equipment:Equipment) - zwraca true tylko
dla NONE
end note

!endif

@enduml