@startuml

class ConsultationRoom{
+getInfo():string
}

!ifndef UKRYJ_NOTATKI

note right of ConsultationRoom
Klasa reprezentująca sale przeznaczoną
do przeprowadzania konsultacji.
Klasa ta dziedziczy z klasy Room.
end note

!endif

@enduml