@startuml

class RehabillitationRoom{
-accessibleEqupiment:vector<equpiment>
-maxCapacity: int
+getInfo():string
+canBeUsed(equipment:Equipment):bool
}

enum Equipment

RehabillitationRoom --> Equipment : lista sprzętu >

!ifndef UKRYJ_NOTATKI

note right of RehabillitationRoom
Klasa reprezentująca sale przeznaczoną
do przeprowadzania zabiegów.
Klasa ta dziedziczy z klasy Room.
accessibleEqupiment - lista sprzętu,
który zawiera pokój
maxCapacity - informuje ile maksymalnie personelu
może się zmieścić w sali.
end note

!endif

@enduml