@startuml

class RehabillitationRoom{
-hasPhysicalTherapyDevices: bool
-hasKinesitherapySpace: bool
-hasRoboticOrSuspensionSystem: bool
-maxCapacity: int
+getInfo():string
}

!ifndef UKRYJ_NOTATKI

note right of RehabillitationRoom
Klasa reprezentująca sale przeznaczoną
do przeprowadzania zabiegów.
Klasa ta dziedziczy z klasy Room.
hasPhysicalTherapyDevices - informuje czy jest zapewniona fizykoterapii - zabiegi "na prąd", światło, zimno i fale.
hasKinesitherapySpace - informuje czy jest zapewniona kinezyterapia - leczenie ruchem / gimnastyka.
hasRoboticOrSuspensionSystem - informuje czy umożilwia rehabilitacje neuromotoryczna
maxCapacity - informuje ile maksymalnie personelu
może się zmieścić w sali.
end note

!endif

@enduml