@startuml

abstract class Room{
-roomNumber:unsigned int
-isActive:unsigned int
+{abstract} getInfo(): string
}

Room <|-- SurgeryRoom
Room <|-- ConsultationRoom

!ifndef UKRYJ_NOTATKI

note right of Room
Abstrakcyjna klasa reprezentująca
sale.
roomNumber - numer sali
isActive - czy sala jest dostępna
end note

!endif

@enduml