@startuml

abstract class Room{
-roomNumber:unsigned int
-isActive:bool
-isArchive:bool
+{abstract} canBeUsed():bool
+{abstract} getInfo(): string
}

Room <|-- RehabillitationRoom
Room <|-- ConsultationRoom

!ifndef UKRYJ_NOTATKI

note right of Room
Abstrakcyjna klasa reprezentująca sale.
roomNumber - numer sali
isActive - czy sala jest dostępna
isArchive - czy jest archiwalny
end note

!endif

@enduml