@startuml

class SurgeryRoom{
-hasLaser: bool
-hasXRay: bool
-maxCapacity: int
+getInfo():string
}

!ifndef UKRYJ_NOTATKI

note right of SurgeryRoom
Klasa reprezentująca sale przeznaczoną
do przeprowadzania zabiegów.
Klasa ta dziedziczy z klasy Room.
hasLaser - informuje czy sala ma laser zabiegowy
hasXRay - informuje czy sala ma sprzęt potrzebny
do przeprowadzania prześwietlenia
maxCapacity - informuje ile maksymalnie personelu
może się zmieścić w sali./
end note

!endif

@enduml