@startuml

class AppointmentRepository{
+get(appointmentId:unsigned int):Appointment
+add(appointment:Appointment):void
+remove(appointment:Appointment):void
+report():string
+size():int
+findBy(predicate:AppointmentPredicate):Appointment[0..*]
+findAll():Appointment[0..*]
}

AppointmentRepository "[0..*]"  -->  Appointment
AppointmentRepository ..>  AppointmentPredicate


!ifndef UKRYJ_NOTATKI

note right of AppointmentRepository
Klasa pełniąca rolę magazynu danych.
Zapewnia standardowy interfejs do
zarządzania obiektami: dodawanie, usuwanie,
pobieranie oraz zaawansowane wyszukiwanie
za pomocą predykatów.
end note

!endif
@enduml