@startuml

class PatientRepository{
+get(personalNumber:string):Patient
+add(patient:Patient):void
+remove(patient:Patient):void
+report():string
+size():int
+findBy(predicate:PatientPredicate):Patient[0..*]
+findAll():Patient[0..*]
}

PatientRepository --> Patient
PatientRepository ..> PatientPredicate
@enduml