@startuml

class PatientRepository{
+loadData(): void
+saveData(): const void
}

PatientRepository "[0..*]" --> Patient
PatientRepository ..> PatientPredicate

!ifndef UKRYJ_NOTATKI

note right of PatientRepository
Klasa przechowująca dane o pacjentach.
Dziedziczy po szablonie RepositoryTemplate.
end note

!endif
@enduml