@startuml

class PatientRepository{
+get(personalNumber:string):Patient
+add(patient:Patient):void
+remove(patient:Patient):void
+report():string
+size():int
+findBy(predicate:PatientPredicate):Patient[0..*]
+findAll():Patient[0..*]
}

PatientRepository "[0..*]" --> Patient
PatientRepository ..> PatientPredicate

!ifndef UKRYJ_NOTATKI

note right of PatientRepository
Klasa pełniąca rolę magazynu danych.
Zapewnia standardowy interfejs do
zarządzania obiektami: dodawanie, usuwanie,
pobieranie oraz zaawansowane wyszukiwanie
za pomocą predykatów.
end note

!endif
@enduml