@startuml

class PersonnelRepository{
+parseData(): void
+dumpData(): string
}

PersonnelRepository  "[0..*]" --> Personnel
PersonnelRepository ..> PersonnelPredicate

!ifndef UKRYJ_NOTATKI

note right of PersonnelRepository
Klasa przechowująca dane o pracownikach.
Dziedziczy po szablonie RepositoryTemplate.
end note

!endif

@enduml