@startuml

abstract class "RepositoryTemplate<T, PredicateT, UniqueParameter>" as RepositoryTemplate {
  -fileName: string
  -vectorOfData: vector<T>

  +RepositoryTemplate(fileName: string)
  +get(i: int): T
  +get(up: UniqueParameter): const T

  +add(t: T): void
  +remove(t: T): void

  +report(): const string
  +size(): const int

  +findBy(predicate: PredicateT): const vector<T>
  +findAll(): const vector<T>&

  +clearVectorOfData(): void

  +loadData(): void
  +saveData(): void
  +{abstract} parseData(): void
  +{abstract} dumpData(): string
}

!ifndef UKRYJ_NOTATKI

note right of RepositoryTemplate
Szablon klasy abstrakcyjnej dla repozytoriów.
Zarządza kolekcją danych w pamięci i wymusza implementację zapisu/odczytu.
clearVectorOfData - czyści wektor z danymi.
get - pobiera obiekt na podstawie indeksu lub unikalnego parametru.
add - dodaje nowy obiekt do repozytorium (ignoruje duplikaty).
remove - usuwa wskazany obiekt z kolekcji.
report - generuje sformatowany raport tekstowy o stanie i zawartości repozytorium.
size - zwraca aktualną liczbę elementów w kolekcji.
findBy - filtruje i wyszukuje elementy spełniające warunek predykatu.
findAll - zwraca pełną listę wszystkich obiektów.
loadData - metoda odczytująca dane z dysku.
saveData - metoda zapisująca dane na dysk.
dumpData - czysto abstrakcyjna klasa do zrzutu danych.
parseData - czysto abstrakcyjna klasa do iterpretacji danych.
end note

!endif

RepositoryTemplate --> "0..*" T : -vectorOfData >

RepositoryTemplate ..> PredicateT
RepositoryTemplate ..> UniqueParameter

RepositoryTemplate <|-- PatientRepository
RepositoryTemplate <|-- PersonnelRepository
RepositoryTemplate <|-- RoomRepository
RepositoryTemplate <|-- ServiceRepository
RepositoryTemplate <|-- AppointmentRepository

@enduml