@startuml

class RoomRepository{
+parseData(): void
+dumpData(): string
}

RoomRepository  "[0..*]" --> Room
RoomRepository ..> RoomPredicate

!ifndef UKRYJ_NOTATKI

note right of RoomRepository
Klasa przechowująca dane o pracownikach.
Dziedziczy po szablonie RepositoryTemplate.
end note

!endif

@enduml