@startuml

class RoomRepository{
+get(roomNumber:unsigned int):Room
+add(room:Room):void
+remove(room:Room):void
+report():string
+size():int
+findBy(predicate:RoomPredicate):Room[0..*]
+findAll():Room[0..*]
}

RoomRepository  "[0..*]" --> Room
RoomRepository ..> RoomPredicate

!ifndef UKRYJ_NOTATKI

note right of RoomRepository
Klasa pełniąca rolę magazynu danych.
Zapewnia standardowy interfejs do
zarządzania obiektami: dodawanie, usuwanie,
pobieranie oraz zaawansowane wyszukiwanie
za pomocą predykatów.
end note

!endif

@enduml