@startuml

class RoomRepository{
+loadData(): void
+saveData(): const void
}

RoomRepository  "[0..*]" --> Room
RoomRepository ..> RoomPredicate

!ifndef UKRYJ_NOTATKI

note right of RoomRepository
Klasa przechowująca dane o pracownikach.
Dziedziczy po szablonie RepositoryTemplate.
end note

!endif

@enduml