@startuml

class ServiceRepository{
+parseData(): void
+dumpData(): string
}

ServiceRepository  "[0..*]" --> Service
ServiceRepository ..> ServicePredicate

!ifndef UKRYJ_NOTATKI

note right of ServiceRepository
Klasa przechowująca dane o usługach.
Dziedziczy po szablonie RepositoryTemplate.
end note

!endif

@enduml