@startuml

abstract class Personnel{
-isActive:bool
-personnelId:unsigned int
+{abstract} getInfo(): string
}

Personnel <|-- Doctor
Personnel <|-- Nurse

!ifndef UKRYJ_NOTATKI

note right of Personnel
Abstrakcyjna klasa reprezentująca
personnel.
Klasa ta dziedziczy z klasy person.
isActive - reprezuntuje czy dany
człowiek przynależący do personelu
jest teraz dostępny.
personnelId - specjalny
idetyifatkor pracownika personelu.
end note

!endif
@enduml