@startuml

class TerminalMenu {
  - logicManager: LogicManagerPtr

  + TerminalMenu()
  + ~TerminalMenu()
  + getLogicManager(): const LogicManagerPtr&
  + start(): void
  + patient(): void
  + appointment(): void
  + room(): void
  + service(): void
  + personnel(): void
  + registerPatient(): bool
  + archivePatient(): bool
  + arrangeAppointment(): bool
  + changeAppointment(): bool
  + addRehabilitationRoom(): bool
  + addConsultationRoom(): bool
  + deactivateRoom(): bool
  + addRehabilitationService(): bool
  + addConsultationService(): bool
  + deactivateService(): bool
  + cancelAppointment(): bool
  + finishAppointment(): bool
  + addNurse(): bool
  + addDoctor(): bool
  + dismissPersonnel(): bool

  - isAmount(tmp: string, amount: int): bool
  - isDigit(znak: char, max: char): int
  - contains<type>(vectorOfValues: vector<type>, value: type, itemName: string): bool
  - checkInt(tmp: string, liczba: unsigned int&): bool
  - displayAll<type>(wektor: vector<type>): void
  - displaySpecific<type>(patient: type, msg: string): bool
  - loadEquipment(accessibleEquipment: vector<Equipment>&): bool
  - jointLoadService(serviceCost: unsigned int&, requiredDocSize: unsigned int&, serviceId: unsigned int&, serviceDuration: unsigned int&, specjalizacja: Specialisation&, serviceName: string&): bool
  - jointLoadPersonnel(firstName: string&, lastName: string&, personnelId: unsigned int&): bool
  - specialisationLoad(spec: Specialisation&): bool
  - findByInt<type, ManagerPtr>(msg: string, manage: ManagerPtr, returnValue: type*): bool
  - isContinue(): bool
  - checkDate(dateInput: string, timeInput: string, parsedTime: ptime&): bool
}

!ifndef UKRYJ_NOTATKI
note right of TerminalMenu
Klasa zapewniająca tekstowe interaktywne menu
do obsługi centrum rehabilitacji.
end note
!endif

TerminalMenu *--> LogicManager : -logicManager >

@enduml