@startuml


!include ../managers/appointmentManager.puml
!include ../managers/patientManager.puml
!include ../managers/personnelManager.puml
!include ../managers/roomManager.puml
!include ../managers/serviceManager.puml

!include ../managers/logicManager.puml

!include ../model/patient/address.puml
!include ../model/patient/patient.puml

!include ../model/personnel/doctor.puml
!include ../model/personnel/nurse.puml
!include ../model/personnel/personnel.puml


!include ../model/rooms/consultationRoom.puml
!include ../model/rooms/rehabilitationRoom.puml
!include ../model/rooms/room.puml

!include ../model/services/consultation.puml
!include ../model/services/rehabillitation.puml
!include ../model/services/service.puml

!include ../model/appointment.puml
!include ../model/person.puml

!include ../repositories/appointmentRepository.puml

!include ../repositories/patientRepository.puml

!include ../repositories/personnelRepository.puml
!include ../repositories/roomRepository.puml
!include ../repositories/serviceRepository.puml

!include ../relationships/specialisationRelationship.puml
!include ../relationships/equipmentRelationship.puml











@enduml