@startuml

'Do pdfa

!include ../managers/LogicManager.puml
!include ../managers/PatientManager.puml
!include ../managers/PersonnelManager.puml
!include ../managers/ServiceManager.puml
!include ../managers/RoomManager.puml

@enduml