@startuml

'Do pdfa

!include ../managers/logicManager.puml
!include ../managers/patientManager.puml
!include ../managers/personnelManager.puml
!include ../managers/serviceManager.puml
!include ../managers/roomManager.puml

@enduml