@startuml

'Do pdfa

!include ../model/patient/Patient.puml
!include ../model/patient/Address.puml
!include ../model/personnel/Doctor.puml
!include ../model/personnel/Nurse.puml
!include ../model/personnel/Personnel.puml
!include ../model/Person.puml

@enduml