@startuml

'Do pdfa

!include ../repositories/patientRepository.puml
!include ../repositories/personnelRepository.puml
!include ../repositories/serviceRepository.puml
!include ../repositories/roomRepository.puml
!include ../repositories/repositoryTemplate.puml
!include ../repositories/appointmentRepository.puml



@enduml