@startuml

!define UKRYJ_NOTATKI

!include ../repositories/patientRepository.puml
!include ../repositories/personnelRepository.puml
!include ../repositories/serviceRepository.puml
!include ../repositories/roomRepository.puml
!include ../repositories/repositoryTemplate.puml



@enduml