@startuml

'Do pdfa

!include ../managers/ManagerTemplate.puml
!include ../managers/ServiceManager.puml
!include ../managers/PatientManager.puml
!include ../managers/PersonnelManager.puml
!include ../managers/RoomManager.puml




@enduml