@startuml

class Patient{
-personalNumber:string
+getInfo():string
}

Patient --> Address

!ifndef UKRYJ_NOTATKI

note right of Patient
Klasa reprezentująca pacjenta.
Klasa ta dziedziczy z klasy person.
personalNumber jest unikatowym pararmetrem
pacjenta.
Klasa pacjenta zawiera w sobie adres jako
share_pointer - wiele kilentów może mieć
taki sam adres.
end note

!endif

@enduml