@startuml

class Patient{
-personalNumber:string
+getInfo():string
}

Patient "zawiera" -->  Address

!ifndef UKRYJ_NOTATKI

note right of Patient
Klasa reprezentująca pacjenta.
Klasa ta dziedziczy z klasy person.
personalNumber jest unikatowym pararmetrem
pacjenta.
end note

!endif

@enduml